# Generated by Django 5.2.6 on 2025-09-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_documento'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
